# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김 지 영
title: Back-end Developer
email: podomat.ex@gmail.com
email_title: email
#phone: Your phone number (optional)
#phone_title: Phone (Phone title override)
#website: https://podomat.github.io
#website_title: blog

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
#github_username:  podomat
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
#about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: |
  C/C++, Golang, Python / Linux, Kubernetes 기반의 Backend/System 개발자입니다.<br>
  
  주로 유무선 통신망 사업자들에게 제공하는 솔루션을 개발하고 유지보수하는 업무를 했습니다.
  대표적인 시스템으로는 `5G core의 service mesh`, `VNF lifecycle 관리 시스템`, `4G IMS의 인스턴트 메시징` 및 `실시간 media 처리 시스템` 등이 있습니다.<br>
  
  현재는 팀 내에서 프로젝트 리더로써 `요구 분석 및 정의`, `시스템 아키텍처 설계`, 
  `코어 파트 구현`, `테스트 및 검수`, `배포 패키지 및 프로젝트 산출물 작성` 등을 주요 업무로 하고 있습니다.<br>

  프로젝트의 완성도를 높이는건 __실력과 의욕이 조화된 멤버들__, 그리고 이들의 프로젝트에 대한 __이해를 깊게 해주는 커뮤니케이션__ 이라고 생각합니다. 
  그래서, `기술 세미나`, `설계 리뷰`, `코드 리뷰`, `장애 리뷰` 등을 진행하면서 멤버들과 함께 성장하는 것을 보람으로 여기고 있습니다.<br>

  저는 이렇게 일합니다.
  - 요구사항이나 문제점을 군더더기 없이 명확하고 논리적인 언어로 정리합니다.
  - 시스템 아키텍처와 소프트웨어 구조, 로직의 흐름을 설계가 된 후에야 코드를 작성합니다.
  - 코드는 간결하고 재사용과 확장성이 고려되며, 의미가 명확하여 누가 보더라도 쉽게 읽혀야 한다고 생각합니다.
  - 주석은 코드를 읽는 데 방해가 되지 않아야 하며, 코드에 담을 수 없는 '의도'를 기록하는 용도로만 절제하여 사용합니다.
  - 로그는 흐름을 빠르게 읽고 문제점을 파악할 수 있도록 시각적으로 깔끔하고 내용은 충분하도록 출력합니다.
  - 작성한 코드에 대한 확신을 가지기 위해 최대한 테스트 코드를 작성하려고 노력합니다.
  - 동료들과 미래의 자신을 위해 코드의 동작, 설정의 의미, 예외 처리 등을 웹 기반 문서로 작성합니다.

content:
  - title: Skills
    layout: list
    content:
      - layout: top-middle
        #title: Company name
        sub_title: 그동안 업무에 사용했던 것들입니다.
      - title: Languages
        description: |
          - C/C++
          - Go
          - Python
          - SQL
          - Shell script
      - title: Frameworks/Solutions
        description: |
          - OS
            - Linux/Unix(Red hat, CentOS, HP-UX, Solaris, etc)
          - Database
            - MariaDB/Mysql, Oracle, Altibase
          - Cloud
            - Kubernetes, Docker, Helm
            - Istio/Envoy, Nats, Harbor
            - Openstack
          - Version Control
            - Git, Subversion, CVS
          - Miscellaneous
            - Make/CMake
            - Flask, Apache HTTP Server
            - Jira, Confluence, Bitbucket, Redmine
      - title: Protocols/Specifications
        description: |
          - TCP, UDP, IP Networking
          - SIP, SDP, RTP/RTCP
          - ETSI NFV, 3GPP 5GC(~Rel.16)
          - HTTP/1.x, HTTP/2
  - title: Experience
    layout: list
    content:
      - layout: top-middle
        sub_title: 그동안 일했던 곳들입니다.
      - title: 텔코웨어
        sub_title: 서버 개발자, 프로젝트 리더
        caption: 2007.06 - present
        link: http://telcoware.com/
        description: |
          - 동사는 이동통신서비스를 위한 CN(Core Network) 분야에서 다양한 솔루션을 개발하고 있음
          - <mark>10개 이상</mark>의 솔루션 개발에서 프로젝트 리더로써 참여하여 **GA 버전 개발 및 상용화** 완료
          - 프로젝트 시작 단계에서 고객사와 미팅을 통해 니즈를 분석하여 요구사항을 정리하고
          - ETSI, 3GPP, RFC 등의 표준 규격을 연구하고 이를 기반으로 서비스 시스템 architecture를 설계하여 솔루션 제안
          - 각 프로젝트에서 프로젝트 리딩과 동시에 주요 모듈 개발을 수행, 높은 KPI달성으로 연말평가에서 <mark>우수사원</mark> 2회 수상
          - 치명적인 버그 및 구조적 이슈로 인해 오픈이 지연된 프로젝트에 긴급 투입되어 **핵심이 되는 문제점들을 정리하고 이것들을 끈질기게 해결하고** 서비스 오픈 완료 경험 2회
      - title: 디노밴
        sub_title: 서버 개발자
        caption: 2002.07 - 2007.06
        link: http://www.dinnovan.com/
        description: |
          - 동사는 유무선 통합 통신 및 메시징 솔루션을 개발하며 주력 제품은 Telephony A/S, Media Server, SMS Center 등이 있음
          - 하드웨어 음성보드를 제어하여 회의통화 및 안내방송 등의 음성(voice) 서비스를 구현할 수 있도록 하는 <mark>API</mark> 개발
          - 서비스 시나리오 hard coding을 탈피하기 위해 voice 서비스 시나리오를 작성하는 tool을 설계하고
          - 이 tool로 만들어진 <mark>시나리오 파일을 로딩</mark>하여 voice 서비스를 제공하는 시스템 개발
          - Linux와 Solaris에서 CPU/Memory/Disc/Network 사용률 등을 H/W 모니터링하여 통계 및 알람을 생성하는 기능 개발
          - C/S Interworking을 위한 IO Multiplexing을 callback 구조의 <mark>framework</mark> 으로 개발하여 사내 개발자들에게 배포
      - title: AGT
        sub_title: 게임로직 개발자
        caption: 2001.07 - 2002.05
        description: |
          - 동사는 멀티 모니터를 이용한 전시영상 시스템 개발을 목표로 설립되었으며 네트워크 게임 또한 개발하였음
          - 네트워크 보드게임(포커, 오목, 오셀로 등)의 승패판단 로직 개발
          - 멀티 모니터 제어를 위한 C/S 통신 모듈 개발
          - 터치 스크린용 화상 키보드 개발
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        sub_title: 그동안 해왔던 일들입니다.
      - layout: left
        title: 3GPP 5GC SCP
        link: https://www.metaswitch.com/blog/the-service-communication-proxy-5g-caught-up-in-a-service-mesh
        link_text: The service communication proxy
        caption: 2021.01 - present
        description: |
          <mark>개요</mark> 5G core network의 Service Mesh 기능을 수행하는 SCP 및 NRF 시스템 구축
          - 기본 Mesh controller로 [Istio](https://istio.io/)/[Envoyproxy](https://www.envoyproxy.io/)를 도입하고 [Microservice Architecture](https://microservices.io/)를 기반으로 전체 시스템 구조를 설계
          - 배포 및 인스턴스 관리를 위한 CRD를 정의하고, [Operator SDK](https://sdk.operatorframework.io/)를 사용하여 [Custom Resource](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) 형태로 배포를 관리하는 [Kubernetes Operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/)를 개발
          - Network Function이 deploy 될 때 sidecar injection 및 label 설정을 위한 [Mutating admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/) 개발
          - Release-15 Network Function에게 NRF 서비스를 제공하기 위한 proxy 인터페이스 기능 개발
      - layout: left
        title: ETSI NFV-MANO
        caption: 2014.01 - 2020.12
        link: https://www.etsi.org/deliver/etsi_gs/nfv-man/001_099/001/01.01.01_60/gs_nfv-man001v010101p.pdf
        link_text: ETSI GS NFV-MAN 001 v1.1.1
        description: |
          <mark>개요</mark> [NFV(Network Functions Virtualization)](https://www.etsi.org/technologies/nfv)를 위한 배포 관리(MANagement and Orchestration) 시스템 구축
          - [Openstack](https://www.openstack.org/)을 통해 VNF의 Lifecycle을 관리하고 [Zabbix](https://www.zabbix.com/)로 물리/가상 자원 모니터링을 처리할 수 있도록 전체 시스템 Architecture 설계
          - Openstack 제어를 위한 [Keystone](https://www.openstack.org/software/releases/xena/components/keystone)(인증), [Nova](https://www.openstack.org/software/releases/xena/components/nova)(Compute), [Neutron](https://www.openstack.org/software/releases/xena/components/neutron)(Networking) 연동 library 개발
          - VNF의 Instantiate, Scale, Terminate 등을 비롯한 여러 Lifecycle Management Operation 기능 개발
          - VNF Package와 VNF Descriptor에 대한 규격을 정의하고 규격서를 작성하여 VNF vendor社들에 배포
          - Unit test 및 Torture test를 위한 tool 개발
      - layout: left
        title: 3GPP/OMA RCS
        link: https://en.wikipedia.org/wiki/Rich_Communication_Services
        link_text: Rich Communication Services
        caption: 2013.01 - 2013.12
        description: |
          <mark>개요</mark> 이동통신 단말 제조사 및 서비스 사업자에 독립적인 [IMS](https://www.3gpp.org/technologies/keywords-acronyms/109-ims) 기반 통합 메세징([Joyn](https://www.gsma.com/futurenetworks/wp-content/uploads/2013/01/SK-Telecom_Launches-Next-Generation-Integrated-Communication-Service-Named-joyn.T_final2-Press-Release.pdf)) 시스템 구축
          - 서비스 오픈을 목전에 두고 메인 프로세스에 지속적으로 크러쉬가 발생하는 문제가 해결되지 않아 <br>他팀 프로젝트였으나 긴급 투입되어
          - SIP 프로토콜로 Instant message를 수신하여 저장하고 Presence Service와 연동하여 메시지를 <br>타겟에 전송하는 모듈에 메모리 관리 버그를 찾아 수정하여 서비스 오픈 성공
          - 이후 해당 모듈의 추가적인 기능 개발 및 유지보수 수행
      - layout: left
        title: NEAT 자동채점 시스템
        caption: 2012.04 - 2013.01
        description: |
          <mark>개요</mark> NLP와 ML을 기반으로 NEAT(국가영어능력 평가시험) 자동채점 시스템 개발
          - Machine learning 기반 Natural language processing 시스템 설계 및 개발
          - legacy 시스템 모듈화
      - layout: left
        title: 3GPP IMS
        link: https://www.3gpp.org/technologies/keywords-acronyms/109-ims
        link_text: IP-Multimedia Subsystem
        caption: 2013.08 - 2014.08
        description: |
          <mark>개요</mark> 유선통신 사업자의 legacy PSTN 시스템을 대체할 IMS 시스템 구축
          - [3GPP IMS](https://www.3gpp.org/technologies/keywords-acronyms/109-ims) 표준 규격 및 고객 요구사항을 분석하고 표준 architecture에 부합하도록 서비스 구조 설계
          - 협력사간 컨소시엄 구조의 시스템에 대해 전체 서비스 측면의 성능시험 tool을 제작하였고
          - 위 tool을 통해 각 서비스 시나리오별 성능 bottleneck을 찾아 report 함으로써 부족했던 성능 시험 기준 통과
          - 기능 및 성능에 대한 인수시험을 완료하고 이후 협력사간 이슈를 조정하며 시스템 유지보수 수행
      - layout: left
        title: BizUC-AS
        caption: 2011.01 - 2016.06
        description: |
          <mark>개요</mark> 기업 고객들을 유치할 수 있는 기업 tenant형 [IMS](https://www.3gpp.org/technologies/keywords-acronyms/109-ims)기반 [UC(Unified Communication)](https://en.wikipedia.org/wiki/Unified_communications) 서비스 시스템 구축
          - 시스템 고도화 및 유지보수 수행
      - layout: left
        title: 콜센터 녹음시스템
        caption: 2007.08 - 2012.12
        description: |
          <mark>개요</mark> 콜센터의 모든 통화를 녹음하면서 실시간으로 음성데이터를 이중화하여 저장하는 시스템 구축
          - Raw socket을 사용하여 양방향 [RTP](https://datatracker.ietf.org/doc/html/rfc3550) packet을 Sniffing 하는 기능 개발
          - 다수의 녹음데이터 저장서버들에게 [RTP](https://datatracker.ietf.org/doc/html/rfc3550) packet을 Multicast로 전송하는 기능 개발
          - Multicast 채널 관리를 위해 [IGMP](https://datatracker.ietf.org/doc/html/rfc4604) protocol interface를 개발
          - 녹음데이터 저장서버에서의 빈번한 disk access를 줄이기 위해 memory 기반으로 buffering & flushing 기능 개발
      - layout: left
        title: C4 Softswitch
        caption: 2010.05 - 2010.09
        description: |
          <mark>개요</mark> 범용 서버를 사용한 IP network 기반 중개 호 처리 시스템 유지보수
          - SIP protocol interface process 설계 및 개발
      - layout: left
        title: 3GPP MGCF/MG
        link: https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=1685
        link_text: 3GPP TS 29.232
        caption: 2008.08 - 2010.04
        description: |
          <mark>개요</mark> [IMS](https://www.3gpp.org/technologies/keywords-acronyms/109-ims)망에 이종망 간 미디어 (변환) 게이트웨이 시스템 유지보수
          - SIP protocol interface process 설계 및 개발
          - 미디어 변환 요청 처리 logic process 설계 및 개발
      - layout: left
        title: 3GPP MRF
        link: https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=1709
        link_text: 3GPP TS 29.333
        caption: 2007.07 - 2009.12
        description: |
          <mark>개요</mark> [IMS](https://www.3gpp.org/technologies/keywords-acronyms/109-ims)망에 Play Announcement, Audio Conference, DTMF Collection 등 미디어 서비스 제공 시스템 구축
          - SIP protocol interface process 설계 및 개발
          - 미디어 서비스 요청 처리 logic process 설계 및 개발
      - layout: left
        title: IEEE DCD
        caption: 2007.08 - 2007.10
        description: | 
          <mark>개요</mark> 이동통신 가입자 단말을 대상으로 Dynamic [Contents Delivery](https://standards.ieee.org/standard/1903_1-2017.html) (Push message) 서비스 시스템 개발
          - GIP 프로토콜 스택 및 Interface process 개발
      - layout: left
        title: 유무선 통합 SMS Center
        caption: 2005.09 - 2007.03
        description: | 
          <mark>개요</mark> 유무선 전화망 통합 SMS 저장 및 전달 시스템 구축
          - 발신자의 메시지를 수신하여 DB에 저장하고, 착신자의 정보를 조회하여 메시지 라우팅하며,
          - 착신 결과에 대한 notification 처리 및 전송 실패시 재전송 처리까지 전반적인 서비스 로직 설계 및 개발
          - HLR, NPDB, VSMSS 등 SMS 송수신 절차에 필요한 외부 시스템의 연동 프로토콜을 분석하고 interface 모듈 설계 및 개발
          - SMS 송수신 DB table 설계 및 interface 모듈 개발
      - layout: left
        title: 지능망 Service Node
        caption: 2004.12 - 2007.03
        description: |
          <mark>개요</mark> 전화망 가입자에게 voice(음성) 서비스를 제공하는 지능망([Intelligent Network](https://en.wikipedia.org/wiki/Intelligent_Network)) Service Node 시스템 구축
          - voice 서비스 시나리오를 작성하는 GUI tool과 이 tool의 output이 될 시나리오 파일 포맷을 설계하고,
          - 작성한 시나리오 파일을 업로드 및 로딩하여 실행하는 'voice 시나리오 실행 환경' 시스템 설계 및 개발
          - 위 GUI tool을 사용하여 여러 voice 서비스 시나리오 개발 (회의통화, 영어학습, 웹투폰 등)
          - Red hat Linux와 Sun Solaris 시스템에 대한 CPU/Memory/Disc/Network 등의 H/W 사용률을 모니터링하여 통계 및 알람을 생성하는 기능 개발
      - layout: left
        title: Voice Board General Interface
        caption: 2003.10 - 2004.04
        description: | 
          <mark>개요</mark> Conference Call 등 전화 서비스를 위한 실시간 음성 합성(mixing) 서비스 시스템 개발
          - [NMS voice board](https://www.artisantg.com/TestMeasurement/67904-1/NMS-Communications-CG6500C-High-Density-PSTN-VoIP-and-Voice-Processing-Platform)(H/W)의 기능을 application에서 편리하게 사용할 수 있도록 H/W SDK에 대한 wrapping library 개발
      - layout: left
        title: 지능형 부가장치
        caption: 2003.01 - 2003.06
        description: |
          <mark>개요</mark> 무선통신망 가입자들을 위한 부가 서비스 제공하는 IP(Intelligence Peripheral) 시스템 개발
          - Network을 통해 ASR/TTS 서비스를 제공하는 Server 시스템을 설계하고
          - [NMS voice board](https://www.artisantg.com/TestMeasurement/67904-1/NMS-Communications-CG6500C-High-Density-PSTN-VoIP-and-Voice-Processing-Platform)(H/W)와 이를 제어하기 위한 SDK를 사용하여 개발
      - layout: left
        title: 전시영상 시스템
        caption: 2002.01 - 2002.05
        description: |
          <mark>개요</mark> 다수의 디스플레이를 네트웍으로 연결하여 단일 디스플레이처럼 보여주는 대형 전시 영상 시스템 개발
          - 멀티모니터에 대한 출력 및 이벤트 수신을 위한 클라이언트/서버 통신 모듈 개발
      - layout: left
        title: 화상키보드
        caption: 2001.09 - 2001.10
        description: |
          <mark>개요</mark> 의료장비를 위한 터치스크린用 화상키보드 개발
          - 1인 프로젝트로 설계, 디자인, 개발 진행.
      - layout: left
        title: WEB용 캐주얼 게임
        caption: 2001.07 - 2001.12
        description: |
          <mark>개요</mark> 모 포털사이트에서 플레이 할 수 있는 캐주얼 게임 개발
          - Network 게임을 위한 게임방 채팅 시스템 개발
          - Network 게임(포커, 오목, 오셀로)에 관한 승패 판단 로직 개발
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: 수원대학교 대학원
        sub_title: Master of Computer Science
        caption: 2000.03 - 2002.02
      - layout: top-middle
        title: 수원대학교
        sub_title: Bachelor of Computer Science
        caption: 1993.03 - 2000.02
      - layout: top-middle
        title: 서울고등학교
        caption: 1990.03 - 1993.02
  - title: Certificate
    layout: list
    content:
      - layout: top-middle
        title: 정보처리기사
        sub_title: 1급
        #caption: 2001.12

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]